import { Helmet } from "react-helmet";


function Layout({children}) {

  return (
    <>
      <Helmet>
        <title>Real Estate App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Helmet>
      
      {children}
    </>
  )
}

export default Layout;